dqn:
  lrate: 0.0005
  discount_factor: 0.99
  polyak_factor: 0.001
  n_step: 5
  epsilon_annealing_steps: 10000
  epsilon_min: 0.01
  memory_capacity: 100000
  batch_size: 64
  adam_eps: 0.0003125
  grad_norm_value: 10.0
  warm_up_steps: 10000
  update_frequency: 4
  v_min: -200.0
  v_max: 200.0
  atoms_dim: 51
  quantiles_dim: 200
  noise_type: 'factorized'
  use_soft_update: False
  use_double_q: True
  use_dueling: False
  distribution_type: 'quantile'
  use_combined_experience_replay: False
  use_state_normalization: False
  state_norm_clip: [-5.0, 5.0]
  logdir: "./output/dqn"
  seed: 1337
ddpg:
  pi_lrate: 0.0001
  qv_lrate: 0.001
  l2_reg_value: 0.001
  pi_grad_norm_value: 0.0
  qv_grad_norm_value: 0.0
  discount_factor: 0.99
  polyak_factor: 0.001
  n_step: 3
  action_limit: [-1.0, 1.0]
  noise_type: "ou"
  mean: 0.0
  sigma: 0.2
  sigma_min: 0.01
  n_step_annealing: 250000
  theta: 0.15
  dt: 0.01
  memory_capacity: 1000000
  batch_size: 64
  warm_up_steps: 10000
  update_frequency: 4
  use_combined_experience_replay: False
  use_state_normalization: False
  state_norm_clip: [-5.0, 5.0]
  logdir: "./output/ddpg"
  seed: 1
td3:
  actor_lrate: 0.001
  critic_lrate: 0.001
  discount_factor: 0.99
  polyak_factor: 0.005
  n_step: 1
  action_limit: [-1.0, 1.0]
  target_noise_limit: [-0.5, 0.5]
  noise_std: 0.1
  target_noise_std: 0.2
  policy_update_frequency: 2
  memory_capacity: 1000000
  batch_size: 100
  warm_up_steps: 10000
  update_frequency: 1
  use_combined_experience_replay: True
  use_state_normalization: False
  state_norm_clip: [-5.0, 5.0]
  logdir: "./output/td3"
  seed: 1
sac:
  pi_lrate: 0.0003
  qvs_lrate: 0.0003
  alpha_lrate: 0.0003
  pi_grad_norm_value: 0.0
  qvs_grad_norm_value: 0.0
  discount_factor: 0.99
  polyak_factor: 0.005
  n_step: 1
  memory_capacity: 1000000
  batch_size: 256
  warm_up_steps: 10000
  update_frequency: 1
  use_combined_experience_replay: True
  use_state_normalization: False
  state_norm_clip: [-5.0, 5.0]
  logdir: "./output/sac"
  seed: 1
